# Generated by Django 5.2 on 2025-04-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
